server:
  port: 8686
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true
            max-age: 3600
      discovery:
        locator:
          enabled: true
