server:
  port: 8082
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/wzw/product/mapper/xml/*.xml
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/uushop?serverTimezone=GMT%2B8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1